name: CI

on: [push, pull_request]

jobs:
  ui-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui_assignment
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: |
          python main.py

  api-test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: ./api_assignment
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        run: |
          python main.py
      
  coding-style:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: check coding style
        run: ruff check --output-format=github        
